"""create parcels table

Revision ID: b7d301d3b5c5
Revises: 6cb73a490cb2
Create Date: 2025-07-28 12:48:20.900650

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7d301d3b5c5"
down_revision: Union[str, Sequence[str], None] = "6cb73a490cb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parcels",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("weight", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column(
            "parcel_price_usd", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "delivery_price_rub", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["parcel_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parcels_session_id"), "parcels", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parcels_session_id"), table_name="parcels")
    op.drop_table("parcels")
    # ### end Alembic commands ###
